# Generated by Django 5.1.1 on 2024-11-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
